version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./.env

  web:
    image: 758493/yamdb_final:v1
    restart: always
    volumes:
      - static_volume:/code/static
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
